### ISSUE TITLE
Timezone ?

### ISSUE THREAD

**Issue by crazy-max** [JFrogDev/artifactory-docker-examples#39]
Currently the timezone for the docker image `docker.bintray.io/jfrog/artifactory-pro` is set to `Etc/UTC`

```
docker exec -it artifactory cat /etc/timezone
```

Would be nice if we can set the timezone through docker-compose file like :

```
version "2"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:5.4.6
    environment:
      TZ: "Europe/Paris"
    ...
```

Thanks!

**Comment by crazy-max** [comment]
For the moment i use my local files (`/etc/timezone` and `/etc/localtime`) as volume in the docker-container :

```
version: '2'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:5.4.6
    ...
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
   ...
```
