### ISSUE TITLE
Why is db password being written to file?

### ISSUE THREAD

**Issue by ju2wheels** [JFrogDev/artifactory-docker-examples#57]
The database password for the docker examples are being written to a file in $ARTIFACTORY_HOME/.dbpassword in this [setDbPassword](https://github.com/JFrogDev/artifactory-docker-examples/blob/master/docker-compose/art-compose#L168-L178) but this file doesnt seem to actually be used anywhere.

It seems like this can be safely dropped. A better way to handle the password in the docker-compose files is also to use standard [.env](https://docs.docker.com/compose/environment-variables/#the-env-file) file with a `ARTIFACTORY_DB_PASSWORD` and the end user can either set the password in the .env file or remove the file in a production environment and pass it in as real environment variable to the docker-compose file.

Then the compose files can be changed to something like this:

```
version: '2'
services:
  postgresql:
    image: docker.bintray.io/postgres:9.5.2
    container_name: postgresql
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=${ARTIFACTORY_DB_PASSWORD}
    volumes:
     - /data/postgresql:/var/lib/postgresql/data
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:5.9.0
    container_name: artifactory
    ports:
     - 8081:8081
    depends_on:
     - postgresql
    links:
     - postgresql
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
    environment:
     - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
     - DB_USER=artifactory
     - DB_PASSWORD=${ARTIFACTORY_DB_PASSWORD}
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
```
